site_name: Cloud Native Architectures
nav:
    - Home: index.md
    - Supply chain:
      - Supply chain optimization: ./supplychain/supplychain.md
      - Perfect order: ./supplychain/perfectorder.md
      - Intelligent order: ./supplychain/intelligentorder.md
      - Demand risk: ./supplychain/demandrisk.md
      - Loss management: ./supplychain/lossmanagement.md
      - Timeliness: ./supplychain/timeliness.md
      - Sustainable supply chain: ./supplychain/sustainablesupplychain.md
    - About: about.md
theme: windmill