site_name: Cloud Native Architectures
nav:
    - Home: index.md
    - Supply Chain:
      - Supply Chain Optimization: ./sustainability/supplychain.md
      - Inventory Management: ./sustainability/perfectorder.md
      - Demand Risk: ./sustainability/demandrisk.md
      - Loss Management: ./sustainability/lossmanagement.md
      - Timeliness: ./sustainability/timeliness.md
      - Last Mile Delivery: ./sustainability/lastmiledelivery.md
    - About: about.md
theme: windmill