site_name: Cloud Native Architectures
nav:
    - Home: index.md
    - Supply chain:
      - Supply chain optimization: ./sustainability/supplychain.md
      - Perfect order: ./sustainability/perfectorder.md
      - Last mile delivery: ./sustainability/lastmiledelivery.md
      - Demand risk: ./sustainability/demandrisk.md
      - Loss management: ./sustainability/lossmanagement.md
      - Timeliness: ./sustainability/timeliness.md
      - Sustainability: ./sustainability/sustainability.md
    - About: about.md
theme: windmill